In [1]:
import pandas as pd
import numpy as np

In [2]:
        alunos = {'Nome':['Ricardo','Pedro','Degmar','Lawrence'],
                  'Nota':[4,7,5.5,9],
                  'Aprovado':['Nao','Sim','Nao','Sim']}
                  
        df = pd.DataFrame(alunos)
        print(df)

       Nome  Nota Aprovado
0   Ricardo   4.0      Nao
1     Pedro   7.0      Sim
2    Degmar   5.5      Nao
3  Lawrence   9.0      Sim


In [3]:
        objeto1 = pd.Series([2,6,9,10,5])
        print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [4]:
        array1 = np.array([2,6,9,10,5])
        print(array1)

[ 2  6  9 10  5]


In [5]:
array2 = np.array([(2,6,9,10,5), (6,12,2,9,10)])
print(array2)

[[ 2  6  9 10  5]
 [ 6 12  2  9 10]]


In [6]:
        objeto2 = pd.Series(array1)
        print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32


In [7]:
        pri_linhas = df.loc[0:2]
        print(pri_linhas)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2   Degmar   5.5      Nao


In [8]:
        pri_linhas = df.loc[0:3]
        print(pri_linhas)

       Nome  Nota Aprovado
0   Ricardo   4.0      Nao
1     Pedro   7.0      Sim
2    Degmar   5.5      Nao
3  Lawrence   9.0      Sim


In [9]:
        novoDF = df.loc[df['Nota']!=9]
        print(novoDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2   Degmar   5.5      Nao


In [10]:
        alunosReprovados = df.loc[df['Aprovado']!='Sim']
        print(alunosReprovados)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
2   Degmar   5.5      Nao


In [11]:
        alunosAprovados = df.loc[df['Aprovado'] =='Sim']
        print(alunosAprovados)

       Nome  Nota Aprovado
1     Pedro   7.0      Sim
3  Lawrence   9.0      Sim
